cargo-features = ["edition2021"]

[package]
name = "ko_o_ri"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stivale2 = { git = "https://github.com/robbie01/stivale2.git" }
x86_64 = "0.14.2"
